/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2014-01-24 at 18:49:36 UTC 
 * Modify at your own risk.
 */

package com.blw.employeeendpoint;

/**
 * Service definition for Employeeendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link EmployeeendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Employeeendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the employeeendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "employeeendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Employeeendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Employeeendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getEmployee".
   *
   * This request holds the parameters needed by the the employeeendpoint server.  After setting any
   * optional parameters, call the {@link GetEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @param email
   * @return the request
   */
  public GetEmployee getEmployee(java.lang.String email) throws java.io.IOException {
    GetEmployee result = new GetEmployee(email);
    initialize(result);
    return result;
  }

  public class GetEmployee extends EmployeeendpointRequest<com.blw.employeeendpoint.model.Employee> {

    private static final String REST_PATH = "employee/{email}";

    /**
     * Create a request for the method "getEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link GetEmployee#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetEmployee#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param email
     * @since 1.13
     */
    protected GetEmployee(java.lang.String email) {
      super(Employeeendpoint.this, "GET", REST_PATH, null, com.blw.employeeendpoint.model.Employee.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetEmployee setAlt(java.lang.String alt) {
      return (GetEmployee) super.setAlt(alt);
    }

    @Override
    public GetEmployee setFields(java.lang.String fields) {
      return (GetEmployee) super.setFields(fields);
    }

    @Override
    public GetEmployee setKey(java.lang.String key) {
      return (GetEmployee) super.setKey(key);
    }

    @Override
    public GetEmployee setOauthToken(java.lang.String oauthToken) {
      return (GetEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public GetEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetEmployee setQuotaUser(java.lang.String quotaUser) {
      return (GetEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetEmployee setUserIp(java.lang.String userIp) {
      return (GetEmployee) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public GetEmployee setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @Override
    public GetEmployee set(String parameterName, Object value) {
      return (GetEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertEmployee".
   *
   * This request holds the parameters needed by the the employeeendpoint server.  After setting any
   * optional parameters, call the {@link InsertEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @param firstName
   * @param lastName
   * @param phoneNumber
   * @param cellNumber
   * @param email
   * @param idNumber
   * @param country
   * @param city
   * @return the request
   */
  public InsertEmployee insertEmployee(java.lang.String firstName, java.lang.String lastName, java.lang.String phoneNumber, java.lang.String cellNumber, java.lang.String email, java.lang.String idNumber, java.lang.String country, java.lang.String city) throws java.io.IOException {
    InsertEmployee result = new InsertEmployee(firstName, lastName, phoneNumber, cellNumber, email, idNumber, country, city);
    initialize(result);
    return result;
  }

  public class InsertEmployee extends EmployeeendpointRequest<com.blw.employeeendpoint.model.Employee> {

    private static final String REST_PATH = "employee/{firstName}/{lastName}/{phoneNumber}/{cellNumber}/{email}/{idNumber}/{country}/{city}";

    /**
     * Create a request for the method "insertEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link InsertEmployee#execute()} method to invoke the remote
     * operation. <p> {@link InsertEmployee#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param firstName
     * @param lastName
     * @param phoneNumber
     * @param cellNumber
     * @param email
     * @param idNumber
     * @param country
     * @param city
     * @since 1.13
     */
    protected InsertEmployee(java.lang.String firstName, java.lang.String lastName, java.lang.String phoneNumber, java.lang.String cellNumber, java.lang.String email, java.lang.String idNumber, java.lang.String country, java.lang.String city) {
      super(Employeeendpoint.this, "POST", REST_PATH, null, com.blw.employeeendpoint.model.Employee.class);
      this.firstName = com.google.api.client.util.Preconditions.checkNotNull(firstName, "Required parameter firstName must be specified.");
      this.lastName = com.google.api.client.util.Preconditions.checkNotNull(lastName, "Required parameter lastName must be specified.");
      this.phoneNumber = com.google.api.client.util.Preconditions.checkNotNull(phoneNumber, "Required parameter phoneNumber must be specified.");
      this.cellNumber = com.google.api.client.util.Preconditions.checkNotNull(cellNumber, "Required parameter cellNumber must be specified.");
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      this.idNumber = com.google.api.client.util.Preconditions.checkNotNull(idNumber, "Required parameter idNumber must be specified.");
      this.country = com.google.api.client.util.Preconditions.checkNotNull(country, "Required parameter country must be specified.");
      this.city = com.google.api.client.util.Preconditions.checkNotNull(city, "Required parameter city must be specified.");
    }

    @Override
    public InsertEmployee setAlt(java.lang.String alt) {
      return (InsertEmployee) super.setAlt(alt);
    }

    @Override
    public InsertEmployee setFields(java.lang.String fields) {
      return (InsertEmployee) super.setFields(fields);
    }

    @Override
    public InsertEmployee setKey(java.lang.String key) {
      return (InsertEmployee) super.setKey(key);
    }

    @Override
    public InsertEmployee setOauthToken(java.lang.String oauthToken) {
      return (InsertEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertEmployee setQuotaUser(java.lang.String quotaUser) {
      return (InsertEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertEmployee setUserIp(java.lang.String userIp) {
      return (InsertEmployee) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String firstName;

    /**

     */
    public java.lang.String getFirstName() {
      return firstName;
    }

    public InsertEmployee setFirstName(java.lang.String firstName) {
      this.firstName = firstName;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String lastName;

    /**

     */
    public java.lang.String getLastName() {
      return lastName;
    }

    public InsertEmployee setLastName(java.lang.String lastName) {
      this.lastName = lastName;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String phoneNumber;

    /**

     */
    public java.lang.String getPhoneNumber() {
      return phoneNumber;
    }

    public InsertEmployee setPhoneNumber(java.lang.String phoneNumber) {
      this.phoneNumber = phoneNumber;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cellNumber;

    /**

     */
    public java.lang.String getCellNumber() {
      return cellNumber;
    }

    public InsertEmployee setCellNumber(java.lang.String cellNumber) {
      this.cellNumber = cellNumber;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public InsertEmployee setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String idNumber;

    /**

     */
    public java.lang.String getIdNumber() {
      return idNumber;
    }

    public InsertEmployee setIdNumber(java.lang.String idNumber) {
      this.idNumber = idNumber;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String country;

    /**

     */
    public java.lang.String getCountry() {
      return country;
    }

    public InsertEmployee setCountry(java.lang.String country) {
      this.country = country;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String city;

    /**

     */
    public java.lang.String getCity() {
      return city;
    }

    public InsertEmployee setCity(java.lang.String city) {
      this.city = city;
      return this;
    }

    @Override
    public InsertEmployee set(String parameterName, Object value) {
      return (InsertEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listEmployee".
   *
   * This request holds the parameters needed by the the employeeendpoint server.  After setting any
   * optional parameters, call the {@link ListEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListEmployee listEmployee() throws java.io.IOException {
    ListEmployee result = new ListEmployee();
    initialize(result);
    return result;
  }

  public class ListEmployee extends EmployeeendpointRequest<com.blw.employeeendpoint.model.CollectionResponseEmployee> {

    private static final String REST_PATH = "employee";

    /**
     * Create a request for the method "listEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link ListEmployee#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListEmployee#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListEmployee() {
      super(Employeeendpoint.this, "GET", REST_PATH, null, com.blw.employeeendpoint.model.CollectionResponseEmployee.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListEmployee setAlt(java.lang.String alt) {
      return (ListEmployee) super.setAlt(alt);
    }

    @Override
    public ListEmployee setFields(java.lang.String fields) {
      return (ListEmployee) super.setFields(fields);
    }

    @Override
    public ListEmployee setKey(java.lang.String key) {
      return (ListEmployee) super.setKey(key);
    }

    @Override
    public ListEmployee setOauthToken(java.lang.String oauthToken) {
      return (ListEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public ListEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListEmployee setQuotaUser(java.lang.String quotaUser) {
      return (ListEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListEmployee setUserIp(java.lang.String userIp) {
      return (ListEmployee) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListEmployee setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListEmployee setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListEmployee set(String parameterName, Object value) {
      return (ListEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeEmployee".
   *
   * This request holds the parameters needed by the the employeeendpoint server.  After setting any
   * optional parameters, call the {@link RemoveEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @param email
   * @return the request
   */
  public RemoveEmployee removeEmployee(java.lang.String email) throws java.io.IOException {
    RemoveEmployee result = new RemoveEmployee(email);
    initialize(result);
    return result;
  }

  public class RemoveEmployee extends EmployeeendpointRequest<Void> {

    private static final String REST_PATH = "employee/{email}";

    /**
     * Create a request for the method "removeEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link RemoveEmployee#execute()} method to invoke the remote
     * operation. <p> {@link RemoveEmployee#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param email
     * @since 1.13
     */
    protected RemoveEmployee(java.lang.String email) {
      super(Employeeendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
    }

    @Override
    public RemoveEmployee setAlt(java.lang.String alt) {
      return (RemoveEmployee) super.setAlt(alt);
    }

    @Override
    public RemoveEmployee setFields(java.lang.String fields) {
      return (RemoveEmployee) super.setFields(fields);
    }

    @Override
    public RemoveEmployee setKey(java.lang.String key) {
      return (RemoveEmployee) super.setKey(key);
    }

    @Override
    public RemoveEmployee setOauthToken(java.lang.String oauthToken) {
      return (RemoveEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveEmployee setQuotaUser(java.lang.String quotaUser) {
      return (RemoveEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveEmployee setUserIp(java.lang.String userIp) {
      return (RemoveEmployee) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public RemoveEmployee setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @Override
    public RemoveEmployee set(String parameterName, Object value) {
      return (RemoveEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateEmployee".
   *
   * This request holds the parameters needed by the the employeeendpoint server.  After setting any
   * optional parameters, call the {@link UpdateEmployee#execute()} method to invoke the remote
   * operation.
   *
   * @param firstName
   * @param lastName
   * @param phoneNumber
   * @param cellNumber
   * @param email
   * @param idNumber
   * @param country
   * @param city
   * @return the request
   */
  public UpdateEmployee updateEmployee(java.lang.String firstName, java.lang.String lastName, java.lang.String phoneNumber, java.lang.String cellNumber, java.lang.String email, java.lang.String idNumber, java.lang.String country, java.lang.String city) throws java.io.IOException {
    UpdateEmployee result = new UpdateEmployee(firstName, lastName, phoneNumber, cellNumber, email, idNumber, country, city);
    initialize(result);
    return result;
  }

  public class UpdateEmployee extends EmployeeendpointRequest<com.blw.employeeendpoint.model.Employee> {

    private static final String REST_PATH = "employee/{firstName}/{lastName}/{phoneNumber}/{cellNumber}/{email}/{idNumber}/{country}/{city}";

    /**
     * Create a request for the method "updateEmployee".
     *
     * This request holds the parameters needed by the the employeeendpoint server.  After setting any
     * optional parameters, call the {@link UpdateEmployee#execute()} method to invoke the remote
     * operation. <p> {@link UpdateEmployee#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param firstName
     * @param lastName
     * @param phoneNumber
     * @param cellNumber
     * @param email
     * @param idNumber
     * @param country
     * @param city
     * @since 1.13
     */
    protected UpdateEmployee(java.lang.String firstName, java.lang.String lastName, java.lang.String phoneNumber, java.lang.String cellNumber, java.lang.String email, java.lang.String idNumber, java.lang.String country, java.lang.String city) {
      super(Employeeendpoint.this, "PUT", REST_PATH, null, com.blw.employeeendpoint.model.Employee.class);
      this.firstName = com.google.api.client.util.Preconditions.checkNotNull(firstName, "Required parameter firstName must be specified.");
      this.lastName = com.google.api.client.util.Preconditions.checkNotNull(lastName, "Required parameter lastName must be specified.");
      this.phoneNumber = com.google.api.client.util.Preconditions.checkNotNull(phoneNumber, "Required parameter phoneNumber must be specified.");
      this.cellNumber = com.google.api.client.util.Preconditions.checkNotNull(cellNumber, "Required parameter cellNumber must be specified.");
      this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      this.idNumber = com.google.api.client.util.Preconditions.checkNotNull(idNumber, "Required parameter idNumber must be specified.");
      this.country = com.google.api.client.util.Preconditions.checkNotNull(country, "Required parameter country must be specified.");
      this.city = com.google.api.client.util.Preconditions.checkNotNull(city, "Required parameter city must be specified.");
    }

    @Override
    public UpdateEmployee setAlt(java.lang.String alt) {
      return (UpdateEmployee) super.setAlt(alt);
    }

    @Override
    public UpdateEmployee setFields(java.lang.String fields) {
      return (UpdateEmployee) super.setFields(fields);
    }

    @Override
    public UpdateEmployee setKey(java.lang.String key) {
      return (UpdateEmployee) super.setKey(key);
    }

    @Override
    public UpdateEmployee setOauthToken(java.lang.String oauthToken) {
      return (UpdateEmployee) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateEmployee setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateEmployee) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateEmployee setQuotaUser(java.lang.String quotaUser) {
      return (UpdateEmployee) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateEmployee setUserIp(java.lang.String userIp) {
      return (UpdateEmployee) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String firstName;

    /**

     */
    public java.lang.String getFirstName() {
      return firstName;
    }

    public UpdateEmployee setFirstName(java.lang.String firstName) {
      this.firstName = firstName;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String lastName;

    /**

     */
    public java.lang.String getLastName() {
      return lastName;
    }

    public UpdateEmployee setLastName(java.lang.String lastName) {
      this.lastName = lastName;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String phoneNumber;

    /**

     */
    public java.lang.String getPhoneNumber() {
      return phoneNumber;
    }

    public UpdateEmployee setPhoneNumber(java.lang.String phoneNumber) {
      this.phoneNumber = phoneNumber;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String cellNumber;

    /**

     */
    public java.lang.String getCellNumber() {
      return cellNumber;
    }

    public UpdateEmployee setCellNumber(java.lang.String cellNumber) {
      this.cellNumber = cellNumber;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String email;

    /**

     */
    public java.lang.String getEmail() {
      return email;
    }

    public UpdateEmployee setEmail(java.lang.String email) {
      this.email = email;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String idNumber;

    /**

     */
    public java.lang.String getIdNumber() {
      return idNumber;
    }

    public UpdateEmployee setIdNumber(java.lang.String idNumber) {
      this.idNumber = idNumber;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String country;

    /**

     */
    public java.lang.String getCountry() {
      return country;
    }

    public UpdateEmployee setCountry(java.lang.String country) {
      this.country = country;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String city;

    /**

     */
    public java.lang.String getCity() {
      return city;
    }

    public UpdateEmployee setCity(java.lang.String city) {
      this.city = city;
      return this;
    }

    @Override
    public UpdateEmployee set(String parameterName, Object value) {
      return (UpdateEmployee) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Employeeendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Employeeendpoint}. */
    @Override
    public Employeeendpoint build() {
      return new Employeeendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link EmployeeendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setEmployeeendpointRequestInitializer(
        EmployeeendpointRequestInitializer employeeendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(employeeendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
